apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-expense
spec:
  selector:
    matchLabels:
      app: tingeso-expense
  template:
    metadata:
      labels:
        app: tingeso-expense
    spec:
      initContainers:
        - name: wait-for-infrastructure
          image: busybox
          # Heurística 5: Prevención de errores. Espera a que MySQL y Config Server respondan.
          command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando infraestructura..."; sleep 5; done;']
      containers:
        - name: tingeso-expense
          image: demishuaccha/tingeso-expense-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:8888"
            - name: MYSQL_HOST
              value: "mysql-service"

            # CORRECCIÓN CLAVE: El nombre debe ser DB_USERNAME para que Spring reemplace el ${DB_USERNAME} del .yaml
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: user_expense

            # CORRECCIÓN CLAVE: El nombre debe ser DB_PASSWORD para el placeholder ${DB_PASSWORD}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: pass_expense

            # URL de conexión (Asegúrate de que en el .yaml no estés usando otro placeholder para la URL)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/expense_db?createDatabaseIfNotExist=true"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-expense-service
spec:
  selector:
    app: tingeso-expense
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP