apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-income
spec:
  selector:
    matchLabels:
      app: tingeso-income
  template:
    metadata:
      labels:
        app: tingeso-income
    spec:
      initContainers:
        - name: wait-for-infrastructure
          image: busybox
          # Heurística 5: Sincronización de infraestructura.
          command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888; do echo "Esperando infraestructura..."; sleep 5; done;']
      containers:
        - name: tingeso-income
          image: demishuaccha/tingeso-income-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:8888"
            - name: MYSQL_HOST
              value: "mysql-service"

            # CORRECCIÓN: Nombres de variables mapeados a los placeholders del Config Server
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: user_income
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: pass_income

            # URL de conexión exclusiva para income_db
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/income_db?createDatabaseIfNotExist=true"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-income-service
spec:
  selector:
    app: tingeso-income
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP