apiVersion: apps/v1
kind: Deployment
metadata:
  name: tingeso-report
spec:
  selector:
    matchLabels:
      app: tingeso-report
  template:
    metadata:
      labels:
        app: tingeso-report
    spec:
      initContainers:
        - name: wait-for-infrastructure
          image: busybox
          # Heurística 5: Sincronización total. Report no arranca hasta que sus fuentes de datos estén vivas.
          command: ['sh', '-c', 'until nc -z mysql-service 3306 && nc -z config-service 8888 && nc -z tingeso-income-service 8080 && nc -z tingeso-expense-service 8080; do echo "Esperando infraestructura y servicios de datos..."; sleep 5; done;']
      containers:
        - name: tingeso-report
          image: demishuaccha/tingeso-report-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-service:8888"

            # CORRECCIÓN: Nombres cortos para inyectar en los placeholders del .yml
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: user_report
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: pass_report

            # Conexión a su propia base de datos
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/report_db?createDatabaseIfNotExist=true"

            # Comunicación interna (Sin Eureka)
            - name: INCOME_SERVICE_URL
              value: "http://tingeso-income-service:8080/api/incomes"
            - name: EXPENSE_SERVICE_URL
              value: "http://tingeso-expense-service:8080/api/expenses"

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 70
            periodSeconds: 20
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 130
            periodSeconds: 30
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: tingeso-report-service
spec:
  selector:
    app: tingeso-report
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP